name:                lix
version:             0.1.0.0
github:              "githubuser/lix"
license:             BSD3
author:              "Berat Ertural"
maintainer:          "berat.ertural@rwth-aachen.de"
copyright:           "2021 Berat Ertural"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/lix#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- haskeline
- transformers

library:
  source-dirs: src

executables:
  lix-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lix

tests:
  lix-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lix
